# Generated by Django 3.2.9 on 2021-11-18 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CutomerDetail',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Full name')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('country_id', models.IntegerField(verbose_name='Country ID')),
                ('formatted_address', models.CharField(max_length=1024, verbose_name='Formatted Address')),
            ],
            options={
                'verbose_name': 'CutomerDetail',
                'verbose_name_plural': 'CutomerDetails',
            },
        ),
        migrations.CreateModel(
            name='EtsyOrder',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('receipt_id', models.IntegerField(verbose_name='Receipt ID')),
                ('listing_id', models.IntegerField(verbose_name='Listing ID')),
                ('buyer_user_id', models.IntegerField(verbose_name='Buyer ID')),
                ('message_from_buyer', models.TextField(blank=True, null=True, verbose_name='Buyer Message')),
                ('was_paid', models.BooleanField(default=True, verbose_name='Is Paid')),
                ('creation_tsz', models.DateTimeField(verbose_name='Created At')),
                ('paid_tsz', models.DateTimeField(verbose_name='Paid At')),
                ('downloaded_tsz', models.DateTimeField(auto_now_add=True, verbose_name='Downloaded At')),
            ],
            options={
                'verbose_name': 'EtsyOrder',
                'verbose_name_plural': 'EtsyOrders',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('receipt_shipping_id', models.IntegerField(primary_key=True, serialize=False)),
                ('carrier_name', models.CharField(max_length=50)),
                ('tracking_code', models.CharField(max_length=50)),
                ('mailing_date', models.DateTimeField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_orders.etsyorder')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Product ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Item Title')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('property_values_size', models.CharField(max_length=12, verbose_name='Size')),
                ('price', models.FloatField(verbose_name='Price')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_orders.etsyorder')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
