# Generated by Django 3.2.9 on 2021-12-05 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyOrder',
            fields=[
                ('receipt_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Receipt ID')),
                ('buyer_user_id', models.IntegerField(verbose_name='Buyer ID')),
                ('message_from_buyer', models.TextField(blank=True, null=True, verbose_name='Buyer Message')),
                ('was_paid', models.BooleanField(default=True, verbose_name='Is Paid')),
                ('grandtotal', models.FloatField(verbose_name='Grand Total')),
                ('is_express', models.BooleanField(default=False, verbose_name='Is Express')),
                ('creation_tsz', models.DateTimeField(verbose_name='Order Date')),
                ('downloaded_tsz', models.DateTimeField(auto_now_add=True, verbose_name='Downloaded')),
            ],
            options={
                'verbose_name': 'Etsy Order',
                'verbose_name_plural': 'Etsy Orders',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipping_id', models.IntegerField(primary_key=True, serialize=False)),
                ('carrier_name', models.CharField(max_length=50)),
                ('tracking_code', models.CharField(max_length=50)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('mailing_date', models.DateTimeField()),
                ('is_express', models.BooleanField(default=False)),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_orders.etsyorder')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Item Title')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('product_id', models.IntegerField(verbose_name='Product ID')),
                ('listing_id', models.IntegerField(verbose_name='Listing ID')),
                ('property_values_size', models.CharField(max_length=12, verbose_name='Size')),
                ('price', models.FloatField(verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='designs.design')),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_orders.etsyorder')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('buyer_user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Buyer Email')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=1024, null=True, verbose_name='County')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('country_id', models.IntegerField(verbose_name='Country ID')),
                ('formatted_address', models.TextField(max_length=1024, verbose_name='Formatted Address')),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_orders.etsyorder')),
            ],
            options={
                'verbose_name': 'Cutomer Detail',
                'verbose_name_plural': 'Cutomer Details',
            },
        ),
    ]
