# Generated by Django 3.2.9 on 2021-11-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
