# Generated by Django 3.2.9 on 2021-11-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutomerdetail',
            name='transaction_id',
            field=models.ManyToManyField(to='etsy_orders.EtsyOrder'),
        ),
    ]
