# Generated by Django 3.2.9 on 2021-11-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_orders', '0002_alter_shipment_tracking_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='order_id',
            new_name='receipt_id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
