# Generated by Django 3.2.9 on 2021-11-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_orders', '0002_auto_20211116_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etsyorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='etsyorder',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='etsyorder',
            name='property_values_size',
        ),
        migrations.RemoveField(
            model_name='etsyorder',
            name='shipped_tsz',
        ),
        migrations.RemoveField(
            model_name='etsyorder',
            name='sku',
        ),
        migrations.AddField(
            model_name='cutomerdetail',
            name='formatted_address',
            field=models.CharField(default='', max_length=1024, verbose_name='Formatted Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cutomerdetail',
            name='country_id',
            field=models.IntegerField(verbose_name='Country ID'),
        ),
        migrations.AlterField(
            model_name='etsyorder',
            name='buyer_user_id',
            field=models.IntegerField(verbose_name='Buyer ID'),
        ),
        migrations.AlterField(
            model_name='etsyorder',
            name='creation_tsz',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='etsyorder',
            name='downloaded_tsz',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Downloaded At'),
        ),
        migrations.AlterField(
            model_name='etsyorder',
            name='listing_id',
            field=models.IntegerField(verbose_name='Listing ID'),
        ),
        migrations.AlterField(
            model_name='etsyorder',
            name='message_from_buyer',
            field=models.TextField(blank=True, null=True, verbose_name='Buyer Message'),
        ),
        migrations.AlterField(
            model_name='etsyorder',
            name='paid_tsz',
            field=models.DateTimeField(verbose_name='Paid At'),
        ),
        migrations.AlterField(
            model_name='etsyorder',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='etsyorder',
            name='receipt_id',
            field=models.IntegerField(verbose_name='Receipt ID'),
        ),
        migrations.AlterField(
            model_name='etsyorder',
            name='transaction_id',
            field=models.IntegerField(verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='etsyorder',
            name='was_paid',
            field=models.BooleanField(default=True, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_values_size',
            field=models.TextField(blank=True, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.TextField(blank=True, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Item Title'),
        ),
    ]
