# Generated by Django 3.2.9 on 2021-11-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_orders', '0002_cutomerdetail_transaction_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CutomerDetail',
            new_name='CustomerDetail',
        ),
    ]
