# Generated by Django 3.2.9 on 2021-11-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_orders', '0003_auto_20211121_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsyorder',
            name='is_express',
            field=models.BooleanField(default=False, verbose_name='Is Express'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_express',
            field=models.BooleanField(default=False),
        ),
    ]
