# Generated by Django 3.2.9 on 2021-11-18 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_orders', '0004_alter_customerdetail_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsyorder',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='etsy_orders.customerdetail'),
            preserve_default=False,
        ),
    ]
