# Generated by Django 3.2.9 on 2021-11-18 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_orders', '0007_auto_20211118_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='transaction_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etsy_orders.etsyorder'),
            preserve_default=False,
        ),
    ]
