# Generated by Django 3.2.9 on 2021-12-05 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etsy_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel2GoShipment',
            fields=[
                ('shipping_line_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('p2g_order_id', models.CharField(max_length=50)),
                ('carrier_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True)),
                ('order_line_hash', models.CharField(max_length=50)),
                ('order_hash', models.CharField(max_length=50)),
                ('collection_date', models.DateTimeField()),
                ('label', models.TextField()),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etsy_orders.etsyorder')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
    ]
