# Generated by Django 3.2.9 on 2021-12-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('design_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('png', models.ImageField(upload_to='designs/pngs')),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
            },
        ),
    ]
